<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNTIyIWu\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNTIyIWu/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNTIyIWu.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNTIyIWu\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerNTIyIWu\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'NTIyIWu',
    'container.build_id' => 'c816a50f',
    'container.build_time' => 1557479084,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNTIyIWu');
