<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Repository\TagRepository' shared autowired service.

return $this->privates['App\Repository\TagRepository'] = new \App\Repository\TagRepository(($this->services['doctrine'] ?? $this->load('getDoctrineService.php')));
